STRING GREET = "Hi!"

GREET = "Yo!"

CLEAR 0
TEXT 0 0 GREET 7
TEXT 6 8 "CAT-32" 12
FLIP

WAIT 10

STRIPE SILLY = "MING" "MONG" "WALLA" "WALLA" "BING" "BONG!"
STRIPE OFFSET = 16 32
STRIPE SHIFT = 2 10

SILLY#3 = "WALLAH"

VAR I = 0
WHILE I<6:
 WAIT 5
 TEXT (OFFSET#0)+(I*(SHIFT#0)) (OFFSET#1)+(I*(SHIFT#1)) SILLY#I 6+I
 FLIP
 I = I+1

FIXME_DEDENT_REQURED: