CLEAR 0

VAR VIDEO_W = 120
VAR VIDEO_H = 160
VAR N = 0
VAR Y_OFFSET = (VIDEO_H-VIDEO_W)/2

WHILE N<VIDEO_W:
  PIXEL N N+Y_OFFSET 7
  PIXEL N (VIDEO_H-Y_OFFSET-1)-N (VIDEO_W-N-1)&&15
  FLIP
  WAIT 1
  N = N+1

FIXME_DEDENT_REQUIRED: